GET http://localhost:8080/api/v1/users
Authorization: bearer 

POST http://localhost:8080/api/v1/users
Content-Type: application/json 

{
  "name": {
    "first": "Test",
    "last": "Testy"
  },
  "address": {
    "street": "123 something St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 2,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "test@gmail.com",
  "isBusiness": true,
  "password": "123456aA!" 
}


POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "Admin@batcave.com",
  "password": "123456aA!"
}


GET http://localhost:8080/api/v1/users/userId
Authorization: bearer 

GET http://localhost:8080/api/v1/users/userId
Authorization: bearer 

PUT http://localhost:8080/api/v1/users/userId
Authorization: bearer 
Content-Type: application/json

{
  "name": {
    "first": "Test2",
    "last": "Testy"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "test@batcave.com",
  "isBusiness": true,
  "password": "123456aA!" 
}

PATCH http://localhost:8080/api/v1/users/userId
Authorization: bearer 
Content-Type: application/json

DELETE http://localhost:8080/api/v1/users/userId
Authorization: bearer 
